version: "2"
services:
  rest-api:
    image: rest-api:1.0
    container_name: rest-api
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=flux-rest
    links:
      - mongo
  mongo:
    image: library/mongo:4.2
    container_name: mongo
    ports:
      - 27017:27017

networks:
  default:
    driver: bridge



